sudo: false

services:
  - docker
  
language: java

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

jdk: oraclejdk8 

cache:
  directories:
  - .autoconf
  - $HOME/.m2

script: mvn clean verify

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
  - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
  
  - export REPO=armandorvila/tasks-api-spring
  
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  
  - docker build --quiet --file src/main/docker/tasks-api-spring/Dockerfile --tag $REPO:$COMMIT .
  
  - docker tag $REPO:$COMMIT $REPO:$TAG
  
  - docker push $REPO