version: '3'

services:  

  tasks-api-mongo:
    container_name: tasks-api-mongo
    image: mongo:3.6
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null

  
  tasks-api-data:
    container_name: tasks-api-data
    image: armandorvila/tasks-api-data
    build:
      context: .
      dockerfile: ./src/main/docker/tasks-api-data/Dockerfile
    depends_on:
      - tasks-api-mongo

  
  tasks-api-spring:
    container_name: tasks-api-spring
    image: armandorvila/tasks-api-spring
    build:
      context: .
      dockerfile: ./src/main/docker/tasks-api-spring/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://tasks-api-mongo:27017/tasks
    depends_on:
      - tasks-api-mongo
      - tasks-api-data