version: '3'
services:
  mongodb:
    container_name: todo-api-mongo
    image: mongo:3.6
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null

  app:
    container_name: todo-api-spring
    image: armandorvila/todo-api-spring
    build:
      context: .
      args:
        - JAR_FILE=target/*.jar
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/tasks
    depends_on:
      - mongodb