spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/tasks
      
      
application:
  security:
    jwt: 
      secret: secret
      token-validity-in-seconds: 1800
  errorHandler:
    debug: false
      
      
      
      

         
